greetings:
  first-greeting: Привет
  re-greeting: Рад снова тебя видеть
  goodbye: aufwiedersehen


condition:
  friend: Игорь
  #friend: Алиса

spring:
  profiles:
    active: Вася
    #active: Аня

  shell:
    interactive:
      enabled: false

logging:
  level:
    root: WARN

life-cycle-demo-enabled: true

---
spring:
  profiles: shell

  shell:
    interactive:
      enabled: true
