spring:
  datasource:
    url: jdbc:mysql://localhost:3306/books?useSSL=false&serverTimezone=Europe/Kiev&allowPublicKeyRetrieval=true
    username: maksy
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    hikari:
      maximum-pool-size: 2
